# Generated by Django 3.1.2 on 2020-11-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='couple_n',
            field=models.IntegerField(default=1, verbose_name='Номер пары'),
            preserve_default=False,
        ),
    ]
