# Generated by Django 3.1.2 on 2020-11-03 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couple', '0002_couple_couple_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple.classrooms', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='day_week',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], default='MON', max_length=3, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple.subjects', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple.teachers', verbose_name='Преподаватель'),
        ),
    ]
